kind: pipeline
type: docker
name: default

trigger:
  branch:
  - master

steps:

- name: docker-build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: git.dev.ex/developer/gate-srv
    registry: http://registry.dev.ex
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest

  when:
    event:
    - push